/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8ea",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3132",
        "primary-fixed": "#dae2ff",
        "primary": "#003d9b",
        "background": "#f8f9fb",
        "on-secondary-fixed-variant": "#374763",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b7c7e8",
        "inverse-primary": "#b2c5ff",
        "surface-tint": "#0c56d0",
        "inverse-on-surface": "#f0f1f3",
        "secondary": "#4f5f7b",
        "surface-container": "#edeef0",
        "outline": "#737685",
        "surface-variant": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "primary-container": "#0052cc",
        "tertiary-container": "#a33500",
        "surface": "#f8f9fb",
        "primary-fixed-dim": "#b2c5ff",
        "on-secondary-container": "#51617e",
        "on-tertiary-container": "#ffc6b2",
        "on-secondary-fixed": "#091c35",
        "tertiary-fixed-dim": "#ffb59b",
        "tertiary-fixed": "#ffdbcf",
        "on-primary-container": "#c4d2ff",
        "tertiary": "#7b2600",
        "on-background": "#191c1e",
        "surface-dim": "#d9dadc",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#434654",
        "on-error": "#ffffff",
        "secondary-fixed": "#d6e3ff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#380d00",
        "surface-container-highest": "#e1e2e4",
        "secondary-container": "#cdddff",
        "on-tertiary-fixed-variant": "#812800",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "outline-variant": "#c3c6d6",
        "surface-bright": "#f8f9fb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "gutter": "20px",
        "sm": "8px",
        "xl": "32px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "container-max": "1440px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
    },
  },
  plugins: [],
}

