import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { pool } from './src/config/database.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

function escapeSqlValue(value) {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE'
  if (typeof value === 'number') return String(value)
  if (value instanceof Date) return `'${value.toISOString()}'`
  if (typeof value === 'object') {
    const jsonStr = JSON.stringify(value).replace(/'/g, "''")
    return `'${jsonStr}'::jsonb`
  }
  const str = String(value).replace(/'/g, "''")
  return `'${str}'`
}

async function dumpDatabase() {
  console.log('🔄 Memulai ekspor skema dan data database...')

  const tables = [
    'app_schema_migrations',
    'users',
    'ticket_queues',
    'user_ticket_queues',
    'karyawan',
    'aset_ti',
    'riwayat_pemakaian_aset',
    'tickets',
    'komentar_tiket',
    'ticket_casp_ratings',
    'log_riwayat_tiket',
    'log_riwayat_aset',
    'log_audit_login',
  ]

  let sqlOutput = `-- ============================================================
-- DATABASE DUMP & SEED (FULL OVERWRITE)
-- Generated at: ${new Date().toISOString()}
-- Database: assets_monitoring
-- ============================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- 1. DROP EXISTING VIEWS AND TABLES
DROP VIEW IF EXISTS daftar_aset_ti_lengkap CASCADE;
`

  for (const table of [...tables].reverse()) {
    sqlOutput += `DROP TABLE IF EXISTS ${table} CASCADE;\n`
  }

  sqlOutput += `\n-- 2. CREATE SCHEMAS & TABLES\n\n`

  // Table DDLs
  sqlOutput += `
-- Table: app_schema_migrations
CREATE TABLE app_schema_migrations (
    version integer NOT NULL,
    name character varying(255) NOT NULL,
    checksum_sha256 character(64) NOT NULL,
    applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    applied_by character varying(255) NOT NULL,
    recovery_proof_id character varying(255) NOT NULL,
    change_id character varying(255),
    execution_ms integer NOT NULL,
    CONSTRAINT app_schema_migrations_pkey PRIMARY KEY (version)
);

-- Table: users
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama character varying(255) NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    role character varying(50) DEFAULT 'user'::character varying NOT NULL,
    permissions jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    deleted_at timestamp without time zone,
    deleted_by_user_id bigint,
    deletion_reason text,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    diperbarui_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: ticket_queues
CREATE TABLE ticket_queues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode character varying(50) NOT NULL UNIQUE,
    nama character varying(255) NOT NULL,
    deskripsi text,
    is_active boolean DEFAULT true NOT NULL,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    diperbarui_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: user_ticket_queues
CREATE TABLE user_ticket_queues (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    queue_id bigint NOT NULL REFERENCES ticket_queues(id) ON DELETE CASCADE,
    is_primary boolean DEFAULT false NOT NULL,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT user_ticket_queues_pkey PRIMARY KEY (user_id, queue_id)
);

-- Table: karyawan
CREATE TABLE karyawan (
    id_karyawan bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik character varying(50) NOT NULL UNIQUE,
    nama_karyawan character varying(255) NOT NULL,
    email_kantor character varying(255),
    lokasi_kerja character varying(100),
    status_karyawan character varying(50),
    jabatan character varying(100),
    folder_karyawan character varying(255),
    tingkat_jabatan character varying(100),
    departemen character varying(100),
    direktorat character varying(100),
    tanggal_mulai_bekerja date,
    jenis_perjanjian_kerja character varying(100),
    status_kepegawaian character varying(100),
    id_atasan_langsung bigint REFERENCES karyawan(id_karyawan) ON DELETE SET NULL,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    diperbarui_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: aset_ti
CREATE TABLE aset_ti (
    id_aset bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_seri character varying(100),
    label_aset character varying(100) NOT NULL UNIQUE,
    spesifikasi text,
    id_karyawan bigint REFERENCES karyawan(id_karyawan) ON DELETE SET NULL,
    lokasi_aset character varying(100),
    tipe_perangkat character varying(50),
    merek character varying(100),
    model character varying(100),
    status_aset character varying(50) DEFAULT 'Tersedia'::character varying,
    kondisi_aset character varying(50) DEFAULT 'Bagus'::character varying,
    catatan_aset text,
    deleted_at timestamp without time zone,
    deleted_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    deletion_reason text,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    diperbarui_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: riwayat_pemakaian_aset
CREATE TABLE riwayat_pemakaian_aset (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aset bigint REFERENCES aset_ti(id_aset) ON DELETE SET NULL,
    label_aset character varying(100) NOT NULL,
    nomor_seri character varying(100),
    tipe_perangkat character varying(50),
    merek character varying(100),
    model character varying(100),
    id_karyawan bigint REFERENCES karyawan(id_karyawan) ON DELETE SET NULL,
    nik character varying(50) NOT NULL,
    nama_karyawan character varying(255) NOT NULL,
    tanggal_mulai timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tanggal_selesai timestamp without time zone,
    catatan text,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: tickets
CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_tiket character varying(50) NOT NULL UNIQUE,
    judul character varying(255) NOT NULL,
    deskripsi text,
    kategori character varying(100) DEFAULT 'Umum'::character varying NOT NULL,
    prioritas character varying(50) DEFAULT 'Medium (3d)'::character varying NOT NULL,
    status_tiket character varying(50) DEFAULT 'Open'::character varying NOT NULL,
    assigned_to character varying(255),
    pelapor character varying(255),
    attachment text,
    queue_id bigint NOT NULL REFERENCES ticket_queues(id),
    pelapor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    assigned_to_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    resolved_at timestamp without time zone,
    resolved_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    deleted_at timestamp without time zone,
    deleted_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    deletion_reason text,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    diperbarui_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: komentar_tiket
CREATE TABLE komentar_tiket (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tiket bigint NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    nama_pengguna character varying(255) NOT NULL,
    role_pengguna character varying(50) DEFAULT 'user'::character varying NOT NULL,
    pesan text NOT NULL,
    attachment text,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: ticket_casp_ratings
CREATE TABLE ticket_casp_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL UNIQUE REFERENCES tickets(id) ON DELETE CASCADE,
    reporter_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    assignee_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    reporter_name_snapshot character varying(255) NOT NULL,
    assignee_name_snapshot character varying(255) NOT NULL,
    rating smallint NOT NULL CONSTRAINT ticket_casp_ratings_rating_check CHECK (rating >= 1 AND rating <= 5),
    feedback text,
    submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: log_riwayat_tiket
CREATE TABLE log_riwayat_tiket (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tiket bigint REFERENCES tickets(id) ON DELETE SET NULL,
    nomor_tiket character varying(50),
    aksi character varying(100) NOT NULL,
    perubahan text NOT NULL,
    oleh_pengguna character varying(255) NOT NULL,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: log_riwayat_aset
CREATE TABLE log_riwayat_aset (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aset bigint REFERENCES aset_ti(id_aset) ON DELETE SET NULL,
    label_aset character varying(100) NOT NULL,
    aksi character varying(100) NOT NULL,
    perubahan text NOT NULL,
    oleh_pengguna character varying(255) NOT NULL,
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: log_audit_login
CREATE TABLE log_audit_login (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pengguna character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    aktifitas character varying(255) NOT NULL,
    ip_address character varying(50),
    browser character varying(255),
    dibuat_pada timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- View: daftar_aset_ti_lengkap
CREATE OR REPLACE VIEW daftar_aset_ti_lengkap AS
 SELECT a.id_aset,
    a.nomor_seri,
    a.label_aset,
    a.spesifikasi,
    k.nik,
    k.nama_karyawan,
    k.departemen,
    k.lokasi_kerja,
    a.tipe_perangkat,
    a.merek,
    a.model,
    a.status_aset,
    a.kondisi_aset,
    a.catatan_aset,
    a.lokasi_aset
   FROM (aset_ti a
     LEFT JOIN karyawan k ON ((a.id_karyawan = k.id_karyawan)))
  WHERE (a.deleted_at IS NULL);
`

  sqlOutput += `\n-- 3. INSERT TABLE DATA & SEEDS\n\n`

  for (const table of tables) {
    const res = await pool.query(`SELECT * FROM ${table} ORDER BY 1 ASC`)
    if (res.rows.length === 0) continue

    sqlOutput += `-- Data for table: ${table} (${res.rows.length} rows)\n`
    const cols = Object.keys(res.rows[0])
    const colList = cols.join(', ')

    for (const row of res.rows) {
      const vals = cols.map((col) => escapeSqlValue(row[col])).join(', ')
      sqlOutput += `INSERT INTO ${table} (${colList}) VALUES (${vals});\n`
    }
    sqlOutput += `\n`
  }

  sqlOutput += `-- 4. RESET SEQUENCES\n\n`
  const sequenceTables = [
    { table: 'users', pk: 'id' },
    { table: 'ticket_queues', pk: 'id' },
    { table: 'karyawan', pk: 'id_karyawan' },
    { table: 'aset_ti', pk: 'id_aset' },
    { table: 'riwayat_pemakaian_aset', pk: 'id' },
    { table: 'tickets', pk: 'id' },
    { table: 'komentar_tiket', pk: 'id' },
    { table: 'ticket_casp_ratings', pk: 'id' },
    { table: 'log_riwayat_tiket', pk: 'id' },
    { table: 'log_riwayat_aset', pk: 'id' },
    { table: 'log_audit_login', pk: 'id' },
  ]

  for (const seq of sequenceTables) {
    sqlOutput += `SELECT setval(pg_get_serial_sequence('${seq.table}', '${seq.pk}'), COALESCE((SELECT MAX(${seq.pk}) FROM ${seq.table}), 1));\n`
  }

  const dumpPath = path.join(__dirname, 'database_dump.sql')
  fs.writeFileSync(dumpPath, sqlOutput, 'utf8')
  console.log(`✅ Dump database berhasil dibuat di: ${dumpPath}`)

  await pool.end()
}

dumpDatabase().catch((err) => {
  console.error('❌ Gagal membuat dump database:', err)
  process.exit(1)
})
